import React, { Component } from 'react'
import Loadable from 'react-loadable';

export const loadable = Loadable({
  loader: () => HackerNewsIndex,
  loading: () => <div>Loading...</div>
});

class HackerNewsIndex extends Component {
  constructor(props) {
  	super(props);	
    this.state = {
    	links: [{
    		id: "1",
    		text: "MuseNet",
    		url: "http://openai.com",
    		submitter: "runesoerensen",
    		commentCount: 11
    	},{
    		id: "2",
    		text: "How to hide from the AI surveillance state with a color printout",
    		url: "http://technologyreview.com",
    		submitter: "hsnewman",
    		commentCount: 87
    	},{
    		id: "3",
    		text: "Speedgate: World’s First Sport Generated by AI",
    		url: "http://nvidia.com",
    		submitter: "Impossible",
    		commentCount: 5
    	},{
    		id: "4",
    		text: "Flutter desktop shells",
    		url: "http://github.com",
    		submitter: "Memosyne",
    		commentCount: 185
    	}]}
  }

  render() {
  	return <div>
  		<h1>Hacker News</h1>
  		<div>{this.renderLinks()}</div>
  	</div>
  }

  renderLinks() {
    return this.state.links.map(function({id, text, url, submitter, commentCount}) {
		return <div className="link-row" key={id}>
			<a href="{url}">{text}</a><br/>
			{submitter}&nbsp;&middot;&nbsp;
			<a className="dim" href="comments">{commentCount} comments</a>
		</div>
	});
  }
}

export default HackerNewsIndex
	